### ISSUE TITLE
It does nothing? 

### ISSUE THREAD

**Issue by Xelbayria** [Edddy/AddMoviePosterToFolder#1]
Hello, 

I've given this a try because I only simply wanted to add poster or cover art to the movie folder. I've run AddMoviePosterToFolder and it doesn't do anything? 

No message or anything. Just normal run and be done it. 

Is there anything I missed? 

### **The version:**

- Windows 10 pro 64bit (latest version to date) 
- .net v5.0.13

### **What I did:**
I included the other files along with the exe in a folder and run it via 

AddMoviePosterToFolder.exe "MypathToMovie/MovieFolder" 

and done. nothing?

**Comment by Edddy** [comment]
Do not include the MovieFolder, because it searches in all the subFolders

DO NOT AddMoviePosterToFolder.exe "C:\Movies\Matrix 4"
DO AddMoviePosterToFolder.exe "C:\Movies"

**Comment by Xelbayria** [comment]
Got it. I know what to do. I'll run a quick test.

**Comment by Xelbayria** [comment]
It's working as it's intended to. You should have made it very clear. 
I honestly thought "Addmoviepostertofolder" meant the movie folder, not the folder that contains all of the movies. I misunderstood your documentation on how to use it. 

😅 Thank you for answering my question.
